server:
  port: 10000

spring:
  application:
    name: other-service-qita

  cache:
    type: redis # 指定缓存类型
  # 对应 RedisProperties 类
  redis:
    host: 192.168.232.111
    port: 6379
    password: # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 0 # Redis 连接超时时间，单位：毫秒。
    # 对应 RedisProperties.Jedis 内部类
   # jedis:  #是Redis的java实现客户端,提供基本类型支持,提供比较全的Redis命令
    lettuce: # 基于Netty框架的事件驱动的高级Redis客户端,用于线程安全同步, 异步和响应使用,支持集群,Sentinel等.目前默认使用这个
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2020clouddb1?serverTimezone=UTC
    username: root
    password: root

mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.yss.springcloud.entity  #所有entity别名所在包