
package com.dhao.webservice.service;

import com.dhao.webservice.entry.oa.dmo.CreateSignSaveDO;
import com.dhao.webservice.entry.oa.dto.CreateOASignVO;
import com.oracle.xmlns.internal.webservices.jaxws_databinding.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OAServiceImpl", targetNamespace = "http://impl.service.webservice.dhao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OAServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.dhao.webservice.service.impl.CreateSignSaveDO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "restoaInfo", targetNamespace = "http://impl.service.webservice.dhao.com/", className = "com.dhao.webservice.service.impl.RestoaInfo")
    @ResponseWrapper(localName = "restoaInfoResponse", targetNamespace = "http://impl.service.webservice.dhao.com/", className = "com.dhao.webservice.service.impl.RestoaInfoResponse")
    @Action(input = "http://impl.service.webservice.dhao.com/OAServiceImpl/restoaInfoRequest", output = "http://impl.service.webservice.dhao.com/OAServiceImpl/restoaInfoResponse")
    public CreateSignSaveDO restoaInfo(
        @WebParam(name = "arg0", targetNamespace = "") CreateOASignVO arg0);

}
