
package com.dhao.webservice.service;

import com.oracle.xmlns.internal.webservices.jaxws_databinding.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWebServiceImpl", targetNamespace = "http://impl.service.webservice.dhao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://impl.service.webservice.dhao.com/", className = "com.dhao.webservice.service.impl.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://impl.service.webservice.dhao.com/", className = "com.dhao.webservice.service.impl.GetUserByIdResponse")
    @Action(input = "http://impl.service.webservice.dhao.com/UserWebServiceImpl/getUserByIdRequest", output = "http://impl.service.webservice.dhao.com/UserWebServiceImpl/getUserByIdResponse")
    public String getUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
