
package com.dhao.webservice.service.impl;

import com.dhao.webservice.service.OAServiceImpl;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OAServiceImplService", targetNamespace = "http://impl.service.webservice.dhao.com/", wsdlLocation = "http://localhost:8088/OAService?wsdl")
public class OAServiceImplService
    extends Service
{

    private final static URL OASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException OASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName OASERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.webservice.dhao.com/", "OAServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/OAService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        OASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public OAServiceImplService() {
        super(__getWsdlLocation(), OASERVICEIMPLSERVICE_QNAME);
    }

    public OAServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OASERVICEIMPLSERVICE_QNAME, features);
    }

    public OAServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, OASERVICEIMPLSERVICE_QNAME);
    }

    public OAServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OASERVICEIMPLSERVICE_QNAME, features);
    }

    public OAServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OAServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OAServiceImpl
     */
    @WebEndpoint(name = "OAServiceImplPort")
    public OAServiceImpl getOAServiceImplPort() {
        return super.getPort(new QName("http://impl.service.webservice.dhao.com/", "OAServiceImplPort"), OAServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OAServiceImpl
     */
    @WebEndpoint(name = "OAServiceImplPort")
    public OAServiceImpl getOAServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.webservice.dhao.com/", "OAServiceImplPort"), OAServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw OASERVICEIMPLSERVICE_EXCEPTION;
        }
        return OASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
