
package com.dhao.webservice.service.impl;

import com.dhao.webservice.service.UserWebServiceImpl;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserWebServiceImplService", targetNamespace = "http://impl.service.webservice.dhao.com/", wsdlLocation = "http://localhost:8088/UserWebService?wsdl")
public class UserWebServiceImplService
    extends Service
{

    private final static URL USERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName USERWEBSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.webservice.dhao.com/", "UserWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/UserWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        USERWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UserWebServiceImplService() {
        super(__getWsdlLocation(), USERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public UserWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, USERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public UserWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserWebServiceImpl
     */
    @WebEndpoint(name = "UserWebServiceImplPort")
    public UserWebServiceImpl getUserWebServiceImplPort() {
        return super.getPort(new QName("http://impl.service.webservice.dhao.com/", "UserWebServiceImplPort"), UserWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWebServiceImpl
     */
    @WebEndpoint(name = "UserWebServiceImplPort")
    public UserWebServiceImpl getUserWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.webservice.dhao.com/", "UserWebServiceImplPort"), UserWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw USERWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return USERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
