server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_cache?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
